
title: Tofunmi Sodimu's Homepage
page-top-title: Oluwatofunmi ('Tofunmi') Sodimu
top-section-bg-text: Robotics / Biomedical Engineer
home-subtitle: Tofunmi Sodimu
copyright-text: '&copy; Tofunmi Sodimu 2024. All Rights Reserved.'
